In [1]:
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
soup = BeautifulSoup(open("orfan_metrics/summary_all_20111209.html"), 'html.parser')

In [3]:
header = [str(x.string) for x in soup.findAll("thead")[0].findAll("tr")[1].findAll("th")][:-4]
rows = [ tuple(str(element.contents[0]) for element in row.findAll("td")[:-4]) for row in soup.findAll("tr") ]

In [4]:
df = pd.DataFrame.from_records(rows[2:], columns=header)
df.index = df["Cluster"]
df = df.sort_values(by ="composite score",ascending=False)

In [5]:
print(df.shape)
df.head()

(32, 21)

,Cluster,# nr seqs,# raw seqs,Score,log RNAcode score,P,ORF length (aa),log ORF length,complexity,min,...,max,# seqs with max complexity,min,avg,max,# seqs with max length,composite score,DNA alignment,protein alignment,RNAcode figure
Cluster,,,,,,,,,,,,,,,,,,,,,
1217,1217,6,6,41.974,1.62,7.704e–10,91,1.96,hi,3.79,...,4.12,1,38,73.67,87,2,7.57,"<a href=""all_nt_aln/cluster1217_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster1217_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster1217_eps/hss-0.eps..."
339b,339b,7,11,33.153,1.52,1.069e–06,110,2.04,hi,3.89,...,4.03,1,63,79.14,106,2,7.52,"<a href=""all_nt_aln/cluster339b_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster339b_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster339b_eps/hss-0.eps..."
211b,211b,7,22,42.949,1.63,3.364e–14,80,1.90,hi,3.72,...,4.12,1,31,62.00,73,2,7.49,"<a href=""all_nt_aln/cluster211b_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster211b_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster211b_eps/hss-0.eps..."
562,562,7,9,39.417,1.60,4.592e–07,61,1.79,hi,3.78,...,4.07,1,29,49.57,59,8,7.39,"<a href=""all_nt_aln/cluster562_DNA.aln.txt"">DN...","<a href=""all_aa_aln/cluster562_AA.aln.txt"">AA</a>","<a href=""rnacode_all/cluster562_eps/hss-0.eps""..."
297a,297a,5,14,26.891,1.43,0.001,106,2.03,hi,3.9,...,3.95,1,59,96.60,106,8,7.38,"<a href=""all_nt_aln/cluster297a_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster297a_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster297a_eps/hss-0.eps..."

In [6]:
#Add cluster sample source info to the table
table3 = pd.read_csv("orfan_metrics/Messina_Table3.csv",sep=";")
table3 = table3[["cluster_id","sample_origin"]]
table3.head()

  cluster_id sample_origin
0       1217         feces
1       339b         feces
2       211b         feces
3        562     CSF,serum
4       297a         feces

In [7]:
df = df.merge(table3,left_on="Cluster",right_on="cluster_id")

In [8]:
df.to_csv("1_out/cluster_stats.csv",index=False)