In [1]:
import pandas as pd
import re
import itertools
import matplotlib_venn
import numpy as np

# 1. Load blast hits , hmmer hits and cluster stats

In [2]:
#Load blast best hits
filt_blast_hits = pd.read_csv("1_out/filtered_blast_best_hits.csv")
print(filt_blast_hits.shape)
#Load hmmer best hits
filt_hmmer_hits = pd.read_csv("1_out/filtered_hmmer_best_hits.csv")
print(filt_hmmer_hits.shape)

all_filt_hits = pd.concat([filt_blast_hits,filt_hmmer_hits],axis=0)
#Load cluster stats
clusters = pd.read_csv("1_out/cluster_stats.csv")
clusters["sample_origin"] = clusters["sample_origin"].apply(lambda x:x.replace(",",";"))

(108, 11)
(51, 9)

In [3]:
print(all_filt_hits.shape)
all_filt_hits.head()

(159, 12)

,best_dmn_e_value,bitscore,cluster,db,e_value,pct_id,q_cov,q_len,query_id,s_description,subject_id,tool
0,NaN,488.0,1073,metahit_2014_cds,1.000000e-135,98.560,100.0,276.0,GB3LKKR01A150I,N074A_GL0017322 [gene] locus=scaffold30187_1...,N074A_GL0017322,blastn
1,NaN,479.0,1073,env_nt,1.000000e-131,98.180,99.0,276.0,GB3LKKR01A150I,gut metagenome genome assembly P2E0-k21-2014-0...,gi|936108378|emb|CEAB01076172.1|,blastn
2,NaN,444.0,1073,metahit_cds,1.010000e-122,95.971,96.0,285.0,contig07331,GL0080651_MH0011_[Complete]_[mRNA]_locus=scaff...,GL0080651_MH0011_[Complete]_[mRNA]_locus=scaff...,blastn
3,NaN,159.0,1073,metahit_pep,3.240000e-48,97.727,96.0,92.0,contig07331,GL0080651_MH0011_[Complete]_[mRNA]_locus=scaff...,GL0080651_MH0011_[Complete]_[mRNA]_locus=scaff...,blastp
4,NaN,133.0,1073,metahit_2014_pep,8.000000e-38,100.000,84.0,82.0,GB3LKKR01CLC55,V1.CD14-0_GL0044222 [gene] locus=scaffold182...,V1.CD14-0_GL0044222,blastp

In [4]:
print(clusters.shape)
clusters.head()

(32, 23)

,Cluster,# nr seqs,# raw seqs,Score,log RNAcode score,P,ORF length (aa),log ORF length,complexity,min,...,min.1,avg.1,max.1,# seqs with max length,composite score,DNA alignment,protein alignment,RNAcode figure,cluster_id,sample_origin
0,1217,6,6,41.974,1.62,7.704e–10,91,1.96,hi,3.79,...,38,73.67,87,2,7.57,"<a href=""all_nt_aln/cluster1217_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster1217_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster1217_eps/hss-0.eps...",1217,feces
1,339b,7,11,33.153,1.52,1.069e–06,110,2.04,hi,3.89,...,63,79.14,106,2,7.52,"<a href=""all_nt_aln/cluster339b_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster339b_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster339b_eps/hss-0.eps...",339b,feces
2,211b,7,22,42.949,1.63,3.364e–14,80,1.90,hi,3.72,...,31,62.00,73,2,7.49,"<a href=""all_nt_aln/cluster211b_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster211b_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster211b_eps/hss-0.eps...",211b,feces
3,562,7,9,39.417,1.60,4.592e–07,61,1.79,hi,3.78,...,29,49.57,59,8,7.39,"<a href=""all_nt_aln/cluster562_DNA.aln.txt"">DN...","<a href=""all_aa_aln/cluster562_AA.aln.txt"">AA</a>","<a href=""rnacode_all/cluster562_eps/hss-0.eps""...",562,CSF;serum
4,297a,5,14,26.891,1.43,0.001,106,2.03,hi,3.90,...,59,96.60,106,8,7.38,"<a href=""all_nt_aln/cluster297a_DNA.aln.txt"">D...","<a href=""all_aa_aln/cluster297a_AA.aln.txt"">AA...","<a href=""rnacode_all/cluster297a_eps/hss-0.eps...",297a,feces

# 2. Summary of db hits per cluster

In [5]:
tmp = [(cluster,hits.shape[0],";".join(hits.db)) for cluster,hits in ( all_filt_hits[["cluster","db"]].drop_duplicates().groupby("cluster") )]
hits_x_cluster = pd.DataFrame.from_records(tmp,columns=["cluster","db_hit_count","dbs"])
print("Cluster families with no annotation: {}".format(clusters.shape[0]-hits_x_cluster.shape[0]))
hits_x_cluster = hits_x_cluster.merge(clusters,left_on="cluster",right_on="Cluster",how="right")[["Cluster","db_hit_count","dbs","sample_origin","composite score","P"]]
print(hits_x_cluster.shape)
hits_x_cluster = hits_x_cluster.sort_values(by="composite score",ascending=False)
hits_x_cluster.head()

Cluster families with no annotation: 3
(32, 6)

,Cluster,db_hit_count,dbs,sample_origin,composite score,P
3,1217,7.0,metahit_cds;env_nt;metahit_2014_cds;metahit_20...,feces,7.57,7.704e–10
16,339b,5.0,metahit_2014_cds;metahit_cds;env_nt;metahit_20...,feces,7.52,1.069e–06
9,211b,5.0,env_nt;metahit_2014_cds;metahit_cds;metahit_pe...,feces,7.49,3.364e–14
29,562,NaN,NaN,CSF;serum,7.39,4.592e–07
13,297a,5.0,metahit_2014_cds;metahit_cds;env_nt;metahit_20...,feces,7.38,0.001

In [6]:
hits_x_cluster.to_csv("2_out/dbhits_x_cluster.csv",index=False,quote="\"")

# 3. Summary of db hits grouped by sample origin

### Hits per db per sample_origin

In [7]:
hits_x_sample_origin = {}
for db in all_filt_hits.db.unique():
    hits_x_sample_origin[db] = hits_x_cluster.groupby("sample_origin").apply(lambda df: sum([(db in x.split(";")) if type(x) is str else False for x in df["dbs"]]))
hits_x_sample_origin = pd.concat(hits_x_sample_origin,axis=1)
hits_x_sample_origin

,env_nr,env_nt,metahit_2014_cds,metahit_2014_pep,metahit_cds,metahit_pep,nr
sample_origin,,,,,,,
CSF;feces,0,1,1,1,1,0,0
CSF;mucus;serum,0,1,0,1,0,0,0
CSF;serum,0,1,0,0,0,0,1
feces,1,23,22,22,17,22,2
serum,0,0,0,0,0,0,1

### Calculate hit count to metahit = (metahit_pep or metahit_cds ), and env = ( env nr or env nt )

In [8]:
hits_x_sample_origin_sum = {}
for db in ["env_","metahit_","metahit_2014"]:
    hits_x_sample_origin_sum[db] = hits_x_cluster.groupby("sample_origin").apply(lambda df: sum([(db in x) if type(x) is str else False for x in df["dbs"]]))
hits_x_sample_origin_sum = pd.concat(hits_x_sample_origin_sum,axis=1)
hits_x_sample_origin_sum

                 env_  metahit_  metahit_2014
sample_origin
CSF;feces           1         1             1
CSF;mucus;serum     1         1             1
CSF;serum           1         0             0
feces              23        23            23
serum               0         0             0

In [9]:
table_2 = pd.concat([hits_x_cluster.groupby("sample_origin").count()["Cluster"],
            hits_x_sample_origin,
            hits_x_sample_origin_sum],axis=1)
table_2.to_csv("2_out/dbhits_x_sample_origin.csv")
table_2

,Cluster,env_nr,env_nt,metahit_2014_cds,metahit_2014_pep,metahit_cds,metahit_pep,nr,env_,metahit_,metahit_2014
sample_origin,,,,,,,,,,,
CSF;feces,1,0,1,1,1,1,0,0,1,1,1
CSF;mucus;serum,2,0,1,0,1,0,0,0,1,1,1
CSF;serum,5,0,1,0,0,0,0,1,1,0,0
feces,23,1,23,22,22,17,22,2,23,23,23
serum,1,0,0,0,0,0,0,1,0,0,0

# 4. Analyze NCBI Environmental hits

In [10]:
#Extract all env hits
env_hits = all_filt_hits[["cluster","db","s_description"]][all_filt_hits.db.apply(lambda x: "env_" in x)].sort_values(by="cluster")
#Parse description to extract the source metagenome
env_hits["env_source"] = env_hits.s_description.apply(lambda x: x.split("metagenome")[0])
env_hits["env_source"] = env_hits["env_source"].apply(lambda x: x.split("[")[1] if "[" in x else x   )
#Annotate clusters with sample origin
env_hits = env_hits.merge(clusters[["Cluster","sample_origin","composite score"]],left_on="cluster",right_on="Cluster")
env_hits = env_hits.drop(["s_description","Cluster"],axis=1)
env_hits.index = env_hits["cluster"]
#Remove duplicates when blastp and hmmsearch hits are the same
env_hits = env_hits.drop_duplicates()
print(env_hits.shape)
env_hits.head()

(27, 5)

        cluster      db        env_source sample_origin  composite score
cluster
1073       1073  env_nt              gut          feces             7.19
113b       113b  env_nt              Gut          feces             6.32
1217       1217  env_nr  marine sediment          feces             7.57
1217       1217  env_nt              gut          feces             7.57
179a       179a  env_nt              gut          feces             7.23

## 4.1 Environmental hits per cluster

In [11]:
tmp = env_hits.groupby("cluster").apply( lambda df: ";".join( "{}({})".format(env_src,"n" if db == "env_nt" else "p") for _,db,env_src in df[["db","env_source"]].drop_duplicates().to_records()) )
env_hits_x_clust = pd.merge(clusters[["Cluster","composite score","sample_origin"]], 
                             pd.DataFrame(tmp,columns=["env_hits"]),
                             left_on="Cluster",right_index=True,how="left").sort_values(by="composite score",ascending=False)
env_hits_x_clust.to_csv("2_out/env_hits_x_cluster.csv",index=False)
env_hits_x_clust.head()

  Cluster  composite score sample_origin                     env_hits
0    1217             7.57         feces  marine sediment (p);gut (n)
1    339b             7.52         feces                      gut (n)
2    211b             7.49         feces                      gut (n)
3     562             7.39     CSF;serum                          NaN
4    297a             7.38         feces                      gut (n)

## 4.2 Environmental hits per sample origin

In [12]:
env_hits_x_sample_type = pd.DataFrame(env_hits.groupby("sample_origin").apply(lambda df: "; ".join("{}({})".format(k,v) for k,v in df.groupby("env_source").count()["cluster"].to_dict().items())))
env_hits_x_sample_type.columns = ["env_hits"]
env_hits_x_sample_type.to_csv("2_out/env_hits_per_sample_origin.csv")
env_hits_x_sample_type

                                                          env_hits
sample_origin
CSF;feces                                                  gut (1)
CSF;mucus;serum                                     wastewater (1)
CSF;serum                                           wastewater (1)
feces            gut (17); Human gut (5); marine sediment (1); ...

# 5. Summarize MetaHIT hits

In [13]:
metahit_hits = all_filt_hits[["cluster","db"]][all_filt_hits.db.apply(lambda x: "metahit_" in x)].sort_values(by="cluster")
metahit_x_cluster = metahit_hits.drop_duplicates().groupby("cluster").apply(lambda df: ";".join(sorted(df.db)))
metahit_x_cluster= pd.DataFrame(metahit_x_cluster.apply(lambda x: x.replace("metahit_","").replace("cds","n").replace("pep","p")),columns=["MetaHIT"])
metahit_x_cluster = pd.merge(clusters[["Cluster","composite score","sample_origin"]], 
                             metahit_x_cluster,
                             left_on="Cluster",right_index=True,how="left")
metahit_x_cluster.sort_values(by="composite score",ascending=False).to_csv("2_out/metahit_hits_x_cluster.csv",index=False)
metahit_x_cluster.head()

  Cluster  composite score sample_origin            MetaHIT
0    1217             7.57         feces  2014_n;2014_p;n;p
1    339b             7.52         feces  2014_n;2014_p;n;p
2    211b             7.49         feces  2014_n;2014_p;n;p
3     562             7.39     CSF;serum                NaN
4    297a             7.38         feces  2014_n;2014_p;n;p

# 6. Hits per database

In [14]:
all_filt_hits[["cluster","db"]].drop_duplicates().groupby("db").count()

                  cluster
db
env_nr                  1
env_nt                 26
metahit_2014_cds       23
metahit_2014_pep       24
metahit_cds            18
metahit_pep            22
nr                      4

# 7. NR/HMP hits

In [15]:
nrhmp_hits = all_filt_hits[all_filt_hits.db.apply(lambda x: "env" not in x and "metahit" not in x )].sort_values(by="cluster")
nrhmp_hits = nrhmp_hits[["cluster","db","tool","s_description"]]
nrhmp_hits.to_csv("2_out/nr_hmp_hits.csv",index=False)
nrhmp_hits

    cluster  db       tool                                      s_description
15     1217  nr     blastp                  unknown [Veillonella sp. CAG:933]
7      1217  nr  hmmsearch                  unknown [Veillonella sp. CAG:933]
42      532  nr  hmmsearch       hypothetical protein [Megamonas rupellensis]
95     565b  nr     blastp  hypothetical protein H257_12751 [Aphanomyces a...
43     565b  nr  hmmsearch  putative replication protein [Phytophthora par...
107    956b  nr     blastp       hypothetical protein [Chlamydia trachomatis]
50     956b  nr  hmmsearch       hypothetical protein [Chlamydia trachomatis]

## Inspect individual hits

In [19]:
all_filt_hits[all_filt_hits.cluster == "1085"][["tool","db","bitscore","pct_id","q_cov","q_len","s_description","subject_id","best_dmn_e_value"]]

,tool,db,bitscore,pct_id,q_cov,q_len,s_description,subject_id,best_dmn_e_value
2,hmmsearch,metahit_2014_pep,31.7,NaN,NaN,NaN,strand:+ start:8853 stop:9821 length:969 star...,160218816-stool1_revised_C882654_1_gene76494,0.00015

In [17]:
metahit_cds_list = set(all_filt_hits[all_filt_hits.db == "metahit_cds"]["cluster"].drop_duplicates().tolist())
metahit_pep_list = set(all_filt_hits[all_filt_hits.db == "metahit_pep"]["cluster"].drop_duplicates().tolist())
env_nt_list = set(all_filt_hits[all_filt_hits.db == "env_nt"]["cluster"].drop_duplicates().tolist())